import { Injectable, Logger } from '@nestjs/common';
import { execFile as execFileCb } from 'child_process';
import { promisify } from 'util';
import * as fs from 'fs/promises';
import * as path from 'path';
import { Task } from './interfaces/task.interface';
import { TaskStateService, GateResult } from '../state/task-state.service';

const execFile = promisify(execFileCb);

@Injectable()
export class PRManagerService {
  private readonly logger = new Logger(PRManagerService.name);
  private readonly repoRoot: string;

  constructor(private readonly taskState: TaskStateService) {
    this.repoRoot = process.env.REPO_ROOT || process.cwd();
  }

  async createPR(task: Task): Promise<number> {
    const body = await this.buildPRBody(task);

    try {
      const { stdout } = await execFile(
        'gh',
        [
          'pr',
          'create',
          '--title',
          task.title,
          '--body',
          body,
          '--head',
          task.branch,
          '--base',
          'main',
        ],
        { cwd: task.worktreePath || this.repoRoot },
      );

      const prNumber = this.parsePRNumber(stdout);
      this.logger.log(`Created PR #${prNumber} for task ${task.id}`);
      return prNumber;
    } catch (err) {
      this.logger.error(`Failed to create PR for task ${task.id}: ${(err as Error).message}`);
      throw err;
    }
  }

  async buildPRBody(task: Task): Promise<string> {
    const changeSummary = await this.getChangeSummary(task);
    const gateResults = await this.taskState.getAllGateResults(task.id);
    const screenshots = await this.getScreenshots(task.id);

    const testResults = this.formatTestResults(gateResults);
    const a11yResults = this.formatAccessibilityResults(gateResults);
    const perfResults = this.formatPerformanceResults(gateResults);
    const designResults = this.formatDesignResults(gateResults);

    let body = `## Summary

${task.description}

## Changes

\`\`\`
${changeSummary}
\`\`\`

## Validation Results

### Tests
${testResults}

### Accessibility
${a11yResults}

### Performance
${perfResults}

### Design Review
${designResults}
`;

    if (screenshots.length > 0) {
      body += `\n## Screenshots\n\n`;
      for (const screenshot of screenshots) {
        body += `![${path.basename(screenshot)}](${screenshot})\n`;
      }
    }

    body += `
## Environment

| Field | Value |
|-------|-------|
| Branch | \`${task.branch}\` |
| Task ID | \`${task.id}\` |
| Cost | $${task.cost.toFixed(4)} |

---
*Generated by THE Dev Team*
`;

    return body;
  }

  async commentOnPR(prNumber: number, body: string): Promise<void> {
    try {
      await execFile(
        'gh',
        ['pr', 'comment', String(prNumber), '--body', body],
        { cwd: this.repoRoot },
      );
      this.logger.debug(`Commented on PR #${prNumber}`);
    } catch (err) {
      this.logger.error(`Failed to comment on PR #${prNumber}: ${(err as Error).message}`);
      throw err;
    }
  }

  async updatePRDescription(prNumber: number, task: Task): Promise<void> {
    const body = await this.buildPRBody(task);
    try {
      await execFile(
        'gh',
        ['pr', 'edit', String(prNumber), '--body', body],
        { cwd: this.repoRoot },
      );
      this.logger.debug(`Updated PR #${prNumber} description`);
    } catch (err) {
      this.logger.error(`Failed to update PR #${prNumber}: ${(err as Error).message}`);
      throw err;
    }
  }

  async getScreenshots(taskId: string): Promise<string[]> {
    const stateRoot = process.env.REPO_ROOT || process.cwd();
    const screenshotsDir = path.join(
      stateRoot,
      '.the-dev-team',
      'state',
      taskId,
      'screenshots',
    );

    try {
      const files = await fs.readdir(screenshotsDir);
      return files
        .filter(f => /\.(png|jpg|jpeg|gif|webp)$/i.test(f))
        .map(f => path.join(screenshotsDir, f));
    } catch {
      return [];
    }
  }

  private parsePRNumber(output: string): number {
    // gh pr create outputs a URL like https://github.com/owner/repo/pull/123
    const match = output.match(/\/pull\/(\d+)/);
    if (match) {
      return parseInt(match[1], 10);
    }

    // Fallback: try to find any number in the output
    const numMatch = output.match(/(\d+)/);
    if (numMatch) {
      return parseInt(numMatch[1], 10);
    }

    this.logger.warn(`Could not parse PR number from output: ${output}`);
    return 0;
  }

  private async getChangeSummary(task: Task): Promise<string> {
    try {
      const { stdout } = await execFile(
        'git',
        ['diff', '--stat', 'main...HEAD'],
        { cwd: task.worktreePath || this.repoRoot },
      );
      return stdout.trim() || 'No changes detected';
    } catch {
      return 'Unable to generate change summary';
    }
  }

  private formatTestResults(gateResults: GateResult[]): string {
    const testGate = gateResults.find(g => g.gate === 'tests');
    if (!testGate) return 'No test results available';
    return testGate.passed
      ? `PASS - All tests passing (attempt ${testGate.attempt})`
      : `FAIL - ${testGate.notes || 'Tests failed'} (attempt ${testGate.attempt})`;
  }

  private formatAccessibilityResults(gateResults: GateResult[]): string {
    const a11yGate = gateResults.find(g => g.gate === 'accessibility');
    if (!a11yGate) return 'Not applicable';
    return a11yGate.passed
      ? `PASS - Accessibility checks passing (attempt ${a11yGate.attempt})`
      : `FAIL - ${a11yGate.notes || 'Accessibility issues found'} (attempt ${a11yGate.attempt})`;
  }

  private formatPerformanceResults(gateResults: GateResult[]): string {
    const perfGate = gateResults.find(g => g.gate === 'performance');
    if (!perfGate) return 'Not applicable';
    return perfGate.passed
      ? `PASS - Performance within thresholds (attempt ${perfGate.attempt})`
      : `FAIL - ${perfGate.notes || 'Performance issues found'} (attempt ${perfGate.attempt})`;
  }

  private formatDesignResults(gateResults: GateResult[]): string {
    const designGate = gateResults.find(g => g.gate === 'design_review');
    if (!designGate) return 'Not applicable';
    return designGate.passed
      ? `PASS - Design review approved (attempt ${designGate.attempt})`
      : `FAIL - ${designGate.notes || 'Design issues found'} (attempt ${designGate.attempt})`;
  }
}
