{{- if .Values.pgweb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pgweb
  labels:
    app: {{ .Release.Name }}-pgweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pgweb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pgweb
    spec:
      containers:
        - name: pgweb
          image: "{{ .Values.pgweb.image.repository }}:{{ .Values.pgweb.image.tag }}"
          imagePullPolicy: {{ .Values.pgweb.image.pullPolicy }}
          ports:
            - containerPort: 8081
          env:
            - name: PGWEB_DATABASE_URL
              value: "postgres://{{ index .Values.env "POSTGRES_USER" }}:{{ index .Values.env "POSTGRES_PASSWORD" }}@{{ .Release.Name }}:{{ .Values.service.port }}/{{ index .Values.env "POSTGRES_DB" }}?sslmode=disable"
            - name: PGWEB_LISTEN_PORT
              value: "8081"
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.pgweb.resources | nindent 12 }}
{{- end }}
