apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "full-stack.database.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.database.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "full-stack.database.selectorLabels" . | nindent 4 }}
