apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "full-stack.database.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.database.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.database.storage.size }}
